<?php

use Phinx\Migration\AbstractMigration;

class CreateTableNew extends AbstractMigration
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-abstractmigration-class
     *
     * The following commands can be used in this method and Phinx will
     * automatically reverse them when rolling back:
     *
     *    createTable
     *    renameTable
     *    addColumn
     *    renameColumn
     *    addIndex
     *    addForeignKey
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */
    public function up()
    {
        $this->table('news', ['id' => false, 'primary_key' => ['id'], 'engine' => 'InnoDB', 'collation' => 'utf8mb4_unicode_ci'])
            ->addColumn('id', 'biginteger',  ['limit' => 20, 'signed' => false, 'identity' => true])
            ->addColumn('title', 'string')
            ->addColumn('slug', 'string')
            ->addColumn('text', 'text')
            ->save();
    }

    public function down()
    {
        parent::down(); // TODO: Change the autogenerated stub
        $this->dropTable('news');
    }

}
